version: "3.8"
services:

  kraft1:
    build: docker/kraft
    container_name: kraft1
    hostname: kraft1
    environment:
      KAFKA_CLUSTER_ID: "n5FANH2RQ7eJ0E3wuyflmA"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/kraft/config/server1.properties:/opt/kafka/config/kraft/server.properties:ro
      - kraft1_data:/data/kraft-combined-logs:rw
    healthcheck:
      test: nc -z kraft1 9192 || exit 1
      interval: 2s
      retries: 5
      start_period: 5s
    ports:
      - "127.0.0.1:9192:9192"

  kraft2:
    build: docker/kraft
    container_name: kraft2
    hostname: kraft2
    environment:
      KAFKA_CLUSTER_ID: "n5FANH2RQ7eJ0E3wuyflmA"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/kraft/config/server2.properties:/opt/kafka/config/kraft/server.properties:ro
      - kraft2_data:/data/kraft-combined-logs:rw
    healthcheck:
      test: nc -z kraft2 9193 || exit 1
      interval: 2s
      retries: 5
      start_period: 5s
    ports:
      - "127.0.0.1:9193:9193"

  kraft3:
    build: docker/kraft
    container_name: kraft3
    hostname: kraft3
    environment:
      KAFKA_CLUSTER_ID: "n5FANH2RQ7eJ0E3wuyflmA"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/kraft/config/server3.properties:/opt/kafka/config/kraft/server.properties:ro
      - kraft3_data:/data/kraft-combined-logs:rw
    healthcheck:
      test: nc -z kraft3 9194 || exit 1
      interval: 2s
      retries: 5
      start_period: 5s
    ports:
      - "127.0.0.1:9194:9194"

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      kraft1:
        condition: service_healthy
    environment:
      KAFKA_BROKERCONNECT: kraft1:9192,kraft2:9193,kraft3:9194
      JVM_OPTS: "-Xms48M -Xmx96M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    healthcheck:
      test: curl --fail --silent http://localhost:9000 --output /dev/null || exit 1
      interval: 5s
      retries: 20
      start_period: 10s

volumes:
  kraft1_data:
  kraft2_data:
  kraft3_data: